version: "3.5"

services:

  rabbit:
    image: "rabbitmq:3.7.16-management"
    restart: "unless-stopped"
    networks:
      - "rmq-sample-network"
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    build: "./"
    image: "rmq-sample"
    command: "node ./src/producer/index.js"
    restart: "unless-stopped"
    networks:
      - "rmq-sample-network"
    environment:
      AMQP_HOST: "rabbit"

  consumer:
    build: "./"
    image: "rmq-sample"
    command: "node ./src/consumer/index.js"
    restart: "unless-stopped"
    networks:
      - "rmq-sample-network"
    environment:
      AMQP_HOST: "rabbit"

networks:

  rmq-sample-network:
    name: "rmq-sample-network"
